---                                                                         
                                                                              
 - name: Update FreeBSD
   hosts: all                                                               
   become: true                                                             
   tasks:                                                                   
     - name: Update all the Packages
       pkgng:                                             
         name: '*'                                                          
         state: latest                                                      
       when: ansible_facts.distribution == "FreeBSD"                                                                       
                                                                              
                                                                              
                                                                              

