  [defaults]                                                                  
  inventory = server_inventory                                                
  private_key = ~/.ssh/ansible                                                

